### ISSUE TITLE
Flarum论坛视频和音频插件问题

### ISSUE THREAD

**Issue by cgfo** [Flarum-Chinese/mediaembed#3]
1. 是否可以考虑关闭自动播放 －
   这点在我的最近回复中会有体现。如果发帖或者回复多个音频文件，会同时播放，影响效果。可以选择手动开启播放。
2. 文本编辑器能否更换下，插入图片可以直接点击拖拽上传。
3. tags 的添加权限，不光是管理员，可否自定义tags的权限。

**Comment by justjavac** [comment]
这儿是 mediaembed 插件的 issues，我会修正第一个问题的。

**Comment by justjavac** [comment]
已修正
