### ISSUE TITLE
SoundCloud多选项解决办法？

### ISSUE THREAD

**Issue by nekomeowww** [Flarum-Chinese/mediaembed#6]
## 多选项
SoundCloud有多种设计，如下
![](http://www.moepicx.cc/images/2016/11/07/a0a390f1780c6b1dc3c0a63b4f851b57.png)
![](http://www.moepicx.cc/images/2016/11/07/e57dddb5d4d3e213db91c9eb48096d0d.png)
## 对比[TextFormmatter · Add_costum.md](https://github.com/s9e/TextFormatter/blob/master/docs/Plugins/MediaEmbed/Add_custom.md)
在README里面有一个[模拟编辑器](http://s9e.github.io/TextFormatter/fatdown.html)可以测试链接，结果如下：
![](http://www.moepicx.cc/images/2016/11/08/30a7335db5a97e366bf677ccd0f111a4.png)
问题在于自定义选项，是否有可能链接到SoundCloud的API，然后在保留目前使用链接就可以自动识别的情况下新增一个功能可以让用户自定义样式？

#### 下面是SoundCloud的iframe
```
<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/291954396&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
```

**Comment by justjavac** [comment]
自定义样式，需要大改动。既然如此，为何不开发一个单独的插件呢

**Comment by nekomeowww** [comment]
可以考虑...先研究一下SoundCloud的API吧
